title: esp.solutions
tagline: >
  elegant, simple & practical solutions for real business value
url: http://esp.solutions
baseurl: ""
permalink: pretty

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

analytics_id: UA-107150532-1

excerpt_separator: "\n===\n"
